### ISSUE TITLE
Looping depends 1.17+

### ISSUE THREAD

**Issue by JustAMatt** [Spicord/BanAnnouncer#47] opened 2021-07-14 22:44 UTC
Pretty much spelt out here: https://github.com/PaperMC/Paper/issues/5992

Just gotta move maxbans "loadbefore" so it's actually before the softdepends.

**Comment by OopsieWoopsie** [comment] 2021-07-15 01:43
Hmmm... MaxBans is already in the loadbefore list.

https://github.com/Spicord/BanAnnouncer/blob/master/src/main/resources/plugin.yml

**Comment by OopsieWoopsie** [comment] 2021-07-15 02:01
Hi, I have read all the messages of the issue you mentioned, and I don't understand what is the issue here.
From what you said in your message (quote) :
> Just gotta move maxbans "loadbefore" so it's actually before the softdepends.
I understand you are saying to put maxbans into the "loadbefore" list, but it is actually into that list: 
https://github.com/Spicord/BanAnnouncer/blob/master/src/main/resources/plugin.yml#L7
Can you explain it better? or does this causes a "loop"? (english is not my native language)

I mention MaxBansPlus in the softdepend and loadbefore lists because I want this expected behaviour:
"I may require MaxBansPlus but I want to load before it"

Now thinking about this it makes me realise that there is likely a logic error :sweat: 
Because with the softdepend use I expect that MaxBans loads before my plugin but with loadbefore I expect to load before it :sweat: 

I have no problem to remove it from the loadbefore list as I just added it to apply a patch on a MaxBans class before the author made the release of the plugin with the patch applied, so I think it's safe to remove it.

**Comment by OopsieWoopsie** [comment] 2021-07-15 02:05
Here's a build I made with the latest commit applied
https://github.com/Spicord/BanAnnouncer/releases/tag/2.3.0-1

**Comment by JustAMatt** [comment] 2021-07-15 17:32
> Here's a build I made with the latest commit applied
> https://github.com/Spicord/BanAnnouncer/releases/tag/2.3.0-1

Hello! Thank you for the quick response! 

Yup basically expecting the plugin to load at the particular order was the looping issue. I would test that build but I personally do not use MaxBans, just banannouncer. It'll be a critical bug fix for those that pair your plugin with MaxBans tho.

**Comment by OopsieWoopsie** [comment] 2021-07-15 21:00
You won't notice any difference then, I will close this issue because the PR I made to the MaxBans project was merged in Nov 2019, and there was an official update after that date so all users with an updated MaxBans version should not experience any problem.

**Closed by OopsieWoopsie** 2021-07-15 21:00 UTC
