### ISSUE TITLE
1.17.1 An error ocurred while extracting the embed files

### ISSUE THREAD

**Issue by YourMayskiy** [Spicord/BanAnnouncer#53] opened 2021-08-16 13:34 UTC
[16:21:31] [Server thread/INFO]: [Spicord] Disabling Spicord...
[16:21:31] [Server thread/INFO]: [Spicord] Loaded 1 bots, 0 disabled.
[16:21:31] [Server thread/INFO]: [Spicord] Registered addon 'Server Information' (spicord::info) by Sheidy
[16:21:31] [Server thread/INFO]: [Spicord] Registered addon 'Plugin List' (spicord::plugins) by Sheidy
[16:21:31] [Server thread/INFO]: [Spicord] Registered addon 'Player List' (spicord::players) by Sheidy
[16:21:31] [Server thread/WARN]: java.lang.RuntimeException: An error ocurred while extracting the embed files
[16:21:31] [Server thread/WARN]: 	at BanAnnouncer_2.3.0.jar//eu.mcdb.ban_announcer.config.Config.<init>(Config.java:59)
[16:21:31] [Server thread/WARN]: 	at BanAnnouncer_2.3.0.jar//eu.mcdb.ban_announcer.bukkit.BanAnnouncerBukkit.enable(BanAnnouncerBukkit.java:44)
[16:21:31] [Server thread/WARN]: 	at Spicord_4.0.0.jar//org.spicord.event.EventHandler.handleSafe(EventHandler.java:10)
[16:21:31] [Server thread/WARN]: 	at Spicord_4.0.0.jar//org.spicord.Spicord.callEvent(Spicord.java:80)
[16:21:31] [Server thread/WARN]: 	at Spicord_4.0.0.jar//org.spicord.Spicord.onLoad(Spicord.java:110)
[16:21:31] [Server thread/WARN]: 	at Spicord_4.0.0.jar//org.spicord.SpicordLoader.load(SpicordLoader.java:74)
[16:21:31] [Server thread/WARN]: 	at Spicord_4.0.0.jar//org.spicord.bukkit.SpicordBukkit.lambda$onEnable$2(SpicordBukkit.java:46)
[16:21:31] [Server thread/WARN]: 	at Spicord_4.0.0.jar//org.spicord.SpicordCommand.handleRestart(SpicordCommand.java:154)
[16:21:31] [Server thread/WARN]: 	at Spicord_4.0.0.jar//eu.mcdb.universal.command.api.UnparametrizedCommandHandler.handle(UnparametrizedCommandHandler.java:29)
[16:21:31] [Server thread/WARN]: 	at Spicord_4.0.0.jar//eu.mcdb.universal.command.api.Command.onCommand(Command.java:180)
[16:21:31] [Server thread/WARN]: 	at Spicord_4.0.0.jar//eu.mcdb.universal.command.BukkitCommandExecutor.onCommand(BukkitCommandExecutor.java:65)
[16:21:31] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:21:31] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:21:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2169)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1980)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1961)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[16:21:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[16:21:31] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[16:21:31] [Server thread/WARN]: Caused by: java.nio.file.NoSuchFileException: plugins/BanAnnouncer_2.3.0.jar
[16:21:31] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[16:21:31] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[16:21:31] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[16:21:31] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[16:21:31] [Server thread/WARN]: 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
[16:21:31] [Server thread/WARN]: 	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[16:21:31] [Server thread/WARN]: 	at java.base/java.nio.file.Files.readAttributes(Files.java:1843)
[16:21:31] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1212)
[16:21:31] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706)
[16:21:31] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:240)
[16:21:31] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:171)
[16:21:31] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:349)
[16:21:31] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:320)
[16:21:31] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:286)
[16:21:31] [Server thread/WARN]: 	at Spicord_4.0.0.jar//eu.mcdb.util.ZipExtractor.<init>(ZipExtractor.java:50)
[16:21:31] [Server thread/WARN]: 	at Spicord_4.0.0.jar//org.spicord.embed.EmbedLoader.extractAndLoad(EmbedLoader.java:93)
[16:21:31] [Server thread/WARN]: 	at BanAnnouncer_2.3.0.jar//eu.mcdb.ban_announcer.config.Config.<init>(Config.java:57)
[16:21:31] [Server thread/WARN]: 	... 32 more

**Comment by OopsieWoopsie** [comment] 2021-08-16 19:32
Hi, is this happening on a clean BanAnnouncer installation? You do not have any old files?

**Comment by YourMayskiy** [comment] 2021-08-17 05:43
This happened during a clean installation

**Comment by OopsieWoopsie** [comment] 2021-08-17 14:08
Please check that your plugins folder has permission to write/create files for the user you are using to start the server

**Comment by OopsieWoopsie** [comment] 2021-08-17 14:13
Okay, I think this is actually something I need to fix. So I will not close the issue.
It seems that the problem is because you are starting your server from a different directory that your server.jar file.
For example, if your server.jar file is located at `/home/myserver/server.jar` but you are actually located at `/root` and execute `java -jar /home/myserver/server.jar` then this problem will happen.
So make sure you start your server from the directory your server.jar file is located.

**Closed** 2021-09-17 22:36 UTC
