### ISSUE TITLE
Tip for fix litebans bug

### ISSUE THREAD

**Issue by Fedee0** [Spicord/BanAnnouncer#52] opened 2021-08-13 20:06 UTC
To fix the litebans bug that sends multiple bans even when it has been run only once you could put that your plugin, in 5 seconds it can only send 1 ban / unban etc.  the time could be editable in the config.

**Comment by OopsieWoopsie** [comment] 2021-08-14 02:09
Hello, thanks for your suggestion on fixing this issue, but the problem is not with BanAnnouncer, so there should not be a workaround in this plugin for fixing something on another plugin. This should be fixed by the LiteBans developer, not me.
Taking that aside and supposing I was going to implement this, your idea is not helpful in any way, BanAnnouncer should be able to send as many (non-bugged) notifications as ocurrs, and not discarded or ignored if they happen before certain time passes from the previous one.
I hope you understand.

**Closed by OopsieWoopsie** 2021-08-14 02:09 UTC
